name: safari_tour_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.4.0
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.4
  image_picker: ^0.8.7
  json_annotation: ^4.8.0
  path_provider: ^2.0.14
  shared_preferences: ^2.0.20

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
